### ISSUE TITLE
compatible transformers module version

### ISSUE THREAD

**Issue by eryk-mazus** [DaoD/ConstraintGraph4NSO#1]
Hi,

What is the required `transformers` library version to run your code ?

I tried to run your code on `sind` dataset, but it appears that `glue_convert_examples_to_features` from `transformers` got depreciated.

I'd be grateful for help. Great work!

**Comment by DaoD** [comment]
Hi,

Please try transformers 2.3.0. 

Feel free to contact me if you have further questions.

Regards,
Yutao
