### ISSUE TITLE
The window_size problem in FirstPhase prepare_data 

### ISSUE THREAD

**Issue by lizequn** [DaoD/ConstraintGraph4NSO#2]
Hi,

Many thanks for presenting your excellent work.

I am trying to reproduce your result on our dataset, but I got some problems.
In prepare_data.py in FirstPhase

https://github.com/DaoD/ConstraintGraph4NSO/blob/ba21d22d524cd78c919c503e7182a3485aeaf194/FirstPhase/prepare_data.py#L293-L296
If I am correct parameter window_size should be set to different values in the following for loop which is 2,3,5 here.

But I did not find this, it seems in the filehander with window_size=3 repeat three times?

Best,
Li

**Comment by DaoD** [comment]
Sorry for the mistake, in my original code, the preprocessing is performed separately for each dataset with different window sizes. I think you can correct it by moving handler into the for-loop.

Regards,
Yutao
